ALTER TABLE dpdp_consents ADD COLUMN IF NOT EXISTS user_type VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER';
ALTER TABLE dpdp_requests ADD COLUMN IF NOT EXISTS user_type VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER';
