// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get app_title => 'Zippyra Staff App';

  @override
  String get auth_login_title => 'Staff Sign In';

  @override
  String get auth_phone_subtitle =>
      'Enter your registered mobile number to continue';

  @override
  String get auth_send_otp => 'Send OTP';

  @override
  String get auth_verify_otp => 'Verify OTP';

  @override
  String get auth_otp_sent_to => 'Enter the 6-digit OTP sent to';

  @override
  String get auth_resend_otp => 'Resend OTP';

  @override
  String get auth_staff_not_registered =>
      'This number isn\'t registered as staff. Ask your store manager to add you.';

  @override
  String get auth_use_pin => 'Use PIN instead';

  @override
  String get auth_use_otp_instead => 'Use OTP instead';

  @override
  String get auth_pin_setup_title => 'Set up Quick PIN';

  @override
  String get auth_pin_setup_later => 'Set up later';

  @override
  String get auth_pin_locked_retry =>
      'PIN locked due to failed attempts. Try OTP login instead.';

  @override
  String get auth_pin_not_set_fallback =>
      'No PIN configured yet. Falling back to OTP login.';

  @override
  String get shift_tab_title => 'Shift & Home';

  @override
  String get shift_start_shift => 'Start Shift';

  @override
  String get shift_end_shift => 'End Shift';

  @override
  String get shift_duration => 'Active Shift Duration';

  @override
  String get shift_quick_actions => 'Quick Actions';

  @override
  String get shift_already_active => 'Shift is already active.';

  @override
  String get shift_ended => 'Shift ended.';

  @override
  String get inventory_tab_title => 'Inventory';

  @override
  String get inventory_low_stock_title => 'Low Stock Alerts';

  @override
  String get inventory_stock_count_title => 'Stock Count';

  @override
  String get inventory_grn_title => 'GRN Receive';

  @override
  String get inventory_submit_count => 'Submit Count';

  @override
  String get inventory_count_saved_offline =>
      'Saved offline — will sync when connected';

  @override
  String get inventory_variance_found => 'Discrepancies Found';

  @override
  String get grn_title => 'Goods Received Notes';

  @override
  String get grn_create_adhoc => 'Create Ad-hoc GRN';

  @override
  String get grn_qc_review => 'QC Review';

  @override
  String get grn_qc_incomplete => 'QC Incomplete — decisions needed';

  @override
  String get grn_already_completed => 'GRN Already Completed';

  @override
  String get pos_assist_tab_title => 'POS Assist';

  @override
  String get pos_cash_payment_title => 'Cash Payment';

  @override
  String get pos_cash_collected => 'Cash Collected (₹)';

  @override
  String get pos_change_due => 'Change Due';

  @override
  String get pos_insufficient_cash => 'Insufficient cash collected';

  @override
  String get pos_payment_confirmed => 'Payment Confirmed';

  @override
  String get devices_tab_title => 'Devices';

  @override
  String get devices_title => 'Store Hardware Devices';

  @override
  String get devices_status_active => 'ACTIVE';

  @override
  String get devices_status_offline => 'OFFLINE';

  @override
  String get devices_status_provisioning => 'PROVISIONING';

  @override
  String get devices_last_seen => 'Last seen';

  @override
  String get devices_alerts_title => 'Unresolved Hardware Alerts';

  @override
  String get devices_resolve => 'Resolve';

  @override
  String get devices_exit_attempts_title => 'Gate Exit & RFID Audit Monitor';

  @override
  String get devices_staff_override => 'Staff Override';

  @override
  String get devices_override_reason => 'Override Reason';

  @override
  String get profile_tab_title => 'Profile';

  @override
  String get common_coming_soon => 'Coming Soon';

  @override
  String get common_unauthorized_role =>
      'Your role does not have permission to access this section';

  @override
  String get pairing_title => 'Pair Staff Device';

  @override
  String get pairing_enter_code =>
      'Enter the 8-character pairing code generated by your Administrator in the Zippyra Admin Platform.';

  @override
  String get pairing_invalid_code => 'Invalid or expired pairing code';

  @override
  String get pairing_expired_code =>
      'Pairing code expired. Please request a new code from Admin.';

  @override
  String get price_check_title => 'Price Check';

  @override
  String get price_check_not_found =>
      'Product not found. Try scanning again or check with your manager.';

  @override
  String get customer_assist_title => 'Customer Assist';

  @override
  String get customer_assist_enter_last4 =>
      'Enter Last 4 Digits of Phone Number';

  @override
  String get customer_assist_no_match =>
      'No active customer found for phone ending in';

  @override
  String get customer_assist_multiple_matches =>
      'Multiple Matches - Select Customer';

  @override
  String get customer_assist_scope_note =>
      'This lookup is scoped to active customer sessions and orders at your store within the last 2 hours for support purposes.';
}
